title: Sneha Miriyala # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
   I am a passionate software developer focused on building user-friendly and seamless web applications. With a strong foundation in front-end technologies and an expanding interest in backend development, I enjoy crafting innovative solutions that merge design with functionality. I am dedicated to continuous learning and problem-solving to deliver high-quality software that makes an impact.
  <br><br>
  <b><i> Software Developer & Tech Enthusiast</i></b>
  <b>Contact:</b>
  <br><br>
   <a href="https://www.linkedin.com/in/sneha-reddy-miriyala/"><img src="images/linkedin.png" data-canonical-src="images/linkedin.png" width="50" height="50" /></a>
  <a href="https://github.com/snehamiriyala"><img src="images/Github.png" data-canonical-src="images/Github.png" width="50" height="50" /></a>
  <a href="mailto: kukkalasneha825@gmail.com"><img src="images/Email.png" data-canonical-src="images/Email.png" width="50" height="50" /></a>  
  
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
