title: Sneha Miriyala # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I am an experienced software developer skilled in building responsive frontend interfaces with React.js and backend solutions with Nodejs. I specialize in designing RESTful APIs, incident management, and creating data-driven dashboards. Proficient in Docker, AWS, and ServiceNow, I’m dedicated to problem-solving, continuous learning, and delivering high-quality solutions.
  <br><br>
  <b><i> Software Developer & Tech Enthusiast</i></b>
  <b>Contact:</b>
  <br><br>
  <a href="https://www.linkedin.com/in/sneha-reddy-miriyala/"><img src="images/linkedin.png" data-canonical-src="images/linkedin.png" width="50" height="50" /></a>
  <a href="https://github.com/snehamiriyala"><img src="images/Github.png" data-canonical-src="images/Github.png" width="50" height="50" /></a>
  <a href="mailto: kukkalasneha825@gmail.com"><img src="images/Email.png" data-canonical-src="images/Email.png" width="50" height="50" /></a>  
  
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
